`include "../define/rv32i_op_define.vh"
`include "../define/pc_control_define.vh"
`include "../define/alu_control_define.vh"
`include "../define/alu_src_control_define.vh"
`include "../define/reg_src_control_define.vh"
`include "../define/lenth_control_define.vh"
`include "../define/mem_control_define.vh"
`include "../define/reg_control_define.vh"